api_platform:
  title: 'ColorSchemes'
  description: 'Create images with color name'
  version: '1.0.0'
  defaults:
    # pagination
    pagination_client_enabled: true
    pagination_client_items_per_page: true
    pagination_items_per_page: 10
  collection:
    # The default order of results.
    order: 'DESC'
    exists_parameter_name: 'not_null' # the URL query parameter to use is now "not_null"
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
    jsonapi: ['application/vnd.api+json']
  swagger:
    versions: [3]
    api_keys:
      JWT:
        name: Authorization
        type: header
  eager_loading:
    max_joins: 1000
